Fixed: Exception when combining any metadata and --latest flags using Python 3.
Steps to reproduce:

Scrape latest @instagram post on a clean working directory:

 python3.7 instagram_scraper/app.py --maximum  1  --include-location  --latest instagram
Searching instagram for profile pic: 100% 1/1 [00:00<00:00, 352.73 images/s]
Searching instagram for posts: 0 media [00:00, ? media/s] Traceback (most recent call last):
  File "instagram_scraper/app.py", line 1393, in <module>]
    main()
  File "instagram_scraper/app.py", line 1387, in main
    scraper.scrape()
  File "instagram_scraper/app.py", line 668, in scrape
    self.merge_json({ 'GraphImages': self.posts }, '{0}/{1}.json'.format(dst, username))
  File "instagram_scraper/app.py", line 1157, in merge_json
    key = merged.keys()[0]
TypeError: 'dict_keys' object is not subscriptable

Fix: use next + itr on dict_keys instead of indexing it.